<?php

namespace App\Support;

use App\Services\KurashScore;

/**
 * What one athlete stands at in a contest.
 *
 * Built by folding that bout's event log, never stored as a column — so taking
 * back a mistaken call and recomputing gives exactly the tally that would have
 * existed had the call never been made.
 *
 * Scores (khalol, yonbosh, chala) are what this athlete was awarded. Penalties
 * (tanbeh, dakki, girrom, madichal) are what was awarded against them: a
 * penalty is recorded on the side that committed it, and whatever it transfers
 * to the opponent arrives as a separate award on the opponent's side. Neither
 * count is ever inferred from the other.
 */
final readonly class ScoreTally
{
    public function __construct(
        public int $khalol = 0,
        public int $yonbosh = 0,
        public int $chala = 0,
        public int $tanbeh = 0,
        public int $dakki = 0,
        public int $girrom = 0,
        public int $madichal = 0,
        /**
         * The part of the above this athlete earned with a technique, rather
         * than was handed by the opponent's penalties.
         *
         * Kept apart because a contest level at time is decided partly on it:
         * two athletes on one yonbosh each are not level if one threw for it
         * and the other was given it when their opponent collected a dakki.
         */
        public int $earnedYonbosh = 0,
        public int $earnedChala = 0,
        /**
         * Sequence number of the most recent penalty against this athlete, or
         * zero for an athlete who has taken none.
         *
         * The last tie-break in the rules is the latest warning: level on
         * everything else, whoever was warned most recently loses. Zero sorting
         * ahead of every real sequence number is what makes "no penalty at all"
         * beat "a penalty, but an early one" without a special case.
         */
        public int $lastPenaltyAt = 0,
        /**
         * Sequence number of the most recent score to this athlete, or zero
         * for one who has not scored.
         *
         * The chronological tie-break: two athletes level on the value of what
         * they hold, on how they earned it and on how many, are separated by
         * who scored last. Recorded as the log's own sequence rather than a
         * clock reading, because two calls inside the same second have an
         * order and a timestamp cannot express it.
         */
        public int $lastScoreAt = 0,
    ) {}

    /**
     * What one call is worth, from the central table.
     *
     * Nothing outside this class reads config('kurash.score_priority') — an
     * unknown call is worth nothing rather than throwing, so a rules edition
     * that adds a call cannot take a live board down before its value is set.
     */
    public static function priorityOf(?string $call): int
    {
        if ($call === null) {
            return 0;
        }

        /** @var array<string, int> $table */
        $table = config('kurash.score_priority', []);

        return (int) ($table[$call] ?? 0);
    }

    /**
     * The most valuable score this athlete holds, or null for none.
     *
     * A contest is decided on this before it is decided on counts, which is
     * what makes a single yonbosh beat any number of chala.
     */
    public function topScore(): ?string
    {
        $held = array_filter([
            KurashScore::KHALOL => $this->khalol,
            KurashScore::YONBOSH => $this->yonbosh,
            KurashScore::CHALA => $this->chala,
        ]);

        if ($held === []) {
            return null;
        }

        // Ordered by the table rather than by the order they are listed above,
        // so moving a value in config moves this with it.
        uksort($held, fn (string $a, string $b): int => self::priorityOf($b) <=> self::priorityOf($a));

        return array_key_first($held);
    }

    public function topPriority(): int
    {
        return self::priorityOf($this->topScore());
    }

    /** How many of one call this athlete holds. */
    public function count(string $call): int
    {
        return match ($call) {
            KurashScore::KHALOL => $this->khalol,
            KurashScore::YONBOSH => $this->yonbosh,
            KurashScore::CHALA => $this->chala,
            KurashScore::TANBEH => $this->tanbeh,
            KurashScore::DAKKI => $this->dakki,
            KurashScore::GIRROM => $this->girrom,
            KurashScore::MADICHAL => $this->madichal,
            default => 0,
        };
    }

    /** How many of one call this athlete earned with a technique. */
    public function earned(string $call): int
    {
        return match ($call) {
            KurashScore::YONBOSH => $this->earnedYonbosh,
            KurashScore::CHALA => $this->earnedChala,
            // A khalol is never generated by a rule, so every one is earned.
            KurashScore::KHALOL => $this->khalol,
            default => 0,
        };
    }

    /**
     * Has this athlete scored enough to end the contest outright?
     *
     * A khalol ends it on the spot, and the configured number of yonbosh add up
     * to one — however each yonbosh was reached, because a yonbosh conceded
     * through the opponent's dakki is a yonbosh on the board. Chala never
     * accumulates into anything larger however many are awarded.
     */
    public function isDecisive(): bool
    {
        return $this->khalol > 0
            || $this->yonbosh >= (int) config('kurash.yonbosh_for_khalol', 2);
    }

    /**
     * Have this athlete's own penalties ended the contest against them?
     *
     * Girrom is immediate. Madichal accumulates to the configured count and
     * transfers nothing on the way there.
     */
    public function isDefeated(): bool
    {
        return $this->girrom > 0
            || $this->madichal >= (int) config('kurash.madichal_for_defeat', 3);
    }

    /** How this athlete's penalties ended it, for the record. */
    public function defeatType(): ?string
    {
        return match (true) {
            $this->girrom > 0 => KurashScore::GIRROM,
            $this->madichal >= (int) config('kurash.madichal_for_defeat', 3) => KurashScore::MADICHAL,
            default => null,
        };
    }

    /**
     * A single number for the scoreboard column and the display screens.
     *
     * Yonbosh in the whole part, chala in the tenths. This is for showing only:
     * nothing compares two contests on it, because ten chala would read as one
     * yonbosh and chala must never add up to one. Ordering goes through
     * compareTo(), which compares the counts themselves. Chala is clamped at 9
     * so the encoding cannot overflow into the yonbosh place.
     */
    public function points(): float
    {
        if ($this->khalol > 0) {
            return 10.0;
        }

        return $this->yonbosh + min($this->chala, 9) / 10;
    }

    /**
     * Rank this tally against the other one, for a contest that reached time.
     *
     * The order the rules give, each step only reached when the one above it
     * was level:
     *
     *   1. score priority   the more valuable score either athlete holds. A
     *                       yonbosh beats any number of chala, however recently
     *                       they were awarded — value comes before recency and
     *                       before count
     *   2. score origin     at that value, the athlete who earned it with a
     *                       technique over one handed the same thing because
     *                       their opponent was penalised
     *   3. counts           how many, working down from the most valuable
     *   4. latest score     whoever scored most recently
     *   5. latest warning   whoever was warned most recently loses
     *
     * Returning zero is a genuine outcome, not a failure to decide: a contest
     * level all the way down is a referee decision, and this method will not
     * invent a winner to avoid asking for one.
     */
    public function compareTo(self $other): int
    {
        // 1. The more valuable score.
        if ($this->topPriority() !== $other->topPriority()) {
            return $this->topPriority() <=> $other->topPriority();
        }

        $top = $this->topScore();

        // 2. How that score was come by. Only meaningful when both hold one:
        //    two athletes who have not scored are level here, not tied on nil.
        if ($top !== null && $this->earned($top) !== $other->earned($top)) {
            return $this->earned($top) <=> $other->earned($top);
        }

        // 3. Counts, most valuable first. Chala never accumulates into a
        //    yonbosh, but more chala still beats fewer.
        foreach ([KurashScore::KHALOL, KurashScore::YONBOSH, KurashScore::CHALA] as $call) {
            if ($this->count($call) !== $other->count($call)) {
                return $this->count($call) <=> $other->count($call);
            }
        }

        // 4. Who scored last. Zero — never scored — loses to any real score,
        //    which falls out of the comparison without a special case.
        if ($this->lastScoreAt !== $other->lastScoreAt) {
            return $this->lastScoreAt <=> $other->lastScoreAt;
        }

        // 5. Reversed on purpose: the *lower* sequence number wins, and zero —
        //    no warning at all — beats every real one.
        if ($this->lastPenaltyAt !== $other->lastPenaltyAt) {
            return $other->lastPenaltyAt <=> $this->lastPenaltyAt;
        }

        return 0;
    }

    /** Does this tally beat the other one outright? */
    public function beats(self $other): bool
    {
        return $this->compareTo($other) > 0;
    }

    public function isLevelWith(self $other): bool
    {
        return $this->compareTo($other) === 0;
    }

    /** Any score at all on the board for this athlete — what jazzo asks about. */
    public function hasScored(): bool
    {
        return $this->khalol > 0 || $this->yonbosh > 0 || $this->chala > 0;
    }

    /** Total penalties of every grade, for the mat screen's summary line. */
    public function penalties(): int
    {
        return $this->tanbeh + $this->dakki + $this->girrom + $this->madichal;
    }

    /** @return array<string, int> */
    public function toArray(): array
    {
        return [
            'khalol' => $this->khalol,
            'yonbosh' => $this->yonbosh,
            'chala' => $this->chala,
            'tanbeh' => $this->tanbeh,
            'dakki' => $this->dakki,
            'girrom' => $this->girrom,
            'madichal' => $this->madichal,
        ];
    }

    /**
     * Fold one live event into the tally.
     *
     * @param  string  $call  one of KurashScore::CALLS
     * @param  string  $origin  KurashScore::ORIGIN_* — how the award came about
     * @param  int  $sequence  the event's per-bout sequence number
     */
    public function with(string $call, string $origin = KurashScore::ORIGIN_MANUAL, int $sequence = 0): self
    {
        $is = fn (string $c): int => $call === $c ? 1 : 0;
        $earned = $origin === KurashScore::ORIGIN_TECHNIQUE;
        $isPenalty = in_array($call, KurashScore::PENALTIES, true);

        return new self(
            khalol: $this->khalol + $is(KurashScore::KHALOL),
            yonbosh: $this->yonbosh + $is(KurashScore::YONBOSH),
            chala: $this->chala + $is(KurashScore::CHALA),
            tanbeh: $this->tanbeh + $is(KurashScore::TANBEH),
            dakki: $this->dakki + $is(KurashScore::DAKKI),
            girrom: $this->girrom + $is(KurashScore::GIRROM),
            madichal: $this->madichal + $is(KurashScore::MADICHAL),
            earnedYonbosh: $this->earnedYonbosh + ($earned ? $is(KurashScore::YONBOSH) : 0),
            earnedChala: $this->earnedChala + ($earned ? $is(KurashScore::CHALA) : 0),
            // Calls arrive in sequence order, so the last one to be folded is
            // the most recent — but max() rather than assignment, so a caller
            // folding out of order cannot corrupt either tie-break.
            lastPenaltyAt: $isPenalty ? max($this->lastPenaltyAt, $sequence) : $this->lastPenaltyAt,
            lastScoreAt: $isPenalty ? $this->lastScoreAt : max($this->lastScoreAt, $sequence),
        );
    }
}
